import { Lead, Task, Note } from '@/lib/types';

// Team members for the Owner dropdown
export const mockTeamMembers = [
  { id: '1', name: 'John Smith', email: 'john@plumbing.com' },
  { id: '2', name: 'Sarah Williams', email: 'sarah@plumbing.com' },
  { id: '3', name: 'Mike Johnson', email: 'mike@plumbing.com' },
  { id: '4', name: 'Lisa Brown', email: 'lisa@plumbing.com' },
];

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    websiteId: 'website-1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@email.com',
    phone: '(555) 234-5678',
    message: 'I need help with a leaky faucet in my kitchen.',
    status: 'new',
    tags: ['urgent', 'residential'],
    sourcePage: '/contact',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'lead-2',
    websiteId: 'website-1',
    firstName: 'Mike',
    lastName: 'Davis',
    email: 'mike.davis@business.com',
    phone: '(555) 345-6789',
    message: 'Looking for commercial plumbing services for our office building.',
    status: 'contacted',
    tags: ['commercial', 'qualified'],
    sourcePage: '/contact',
    ownerId: '1',
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: 'lead-3',
    websiteId: 'website-1',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'emily.r@email.com',
    phone: '(555) 456-7890',
    message: 'Need a quote for bathroom renovation plumbing.',
    status: 'in_progress',
    tags: ['residential', 'hot lead'],
    sourcePage: '/services',
    ownerId: '2',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: 'lead-4',
    websiteId: 'website-1',
    firstName: 'David',
    lastName: 'Chen',
    email: 'david.chen@email.com',
    phone: '(555) 567-8901',
    message: 'Emergency - burst pipe in basement!',
    status: 'closed',
    tags: ['urgent', 'residential'],
    sourcePage: '/contact',
    ownerId: '3',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: 'lead-5',
    websiteId: 'website-1',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    email: 'jennifer.m@email.com',
    phone: '(555) 678-9012',
    message: 'Interested in water heater replacement.',
    status: 'contacted',
    tags: ['residential', 'qualified'],
    sourcePage: '/services',
    ownerId: '1',
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: 'lead-6',
    websiteId: 'website-1',
    firstName: 'Robert',
    lastName: 'Taylor',
    email: 'robert.t@company.com',
    phone: '(555) 789-0123',
    message: 'Need annual maintenance for our restaurant plumbing.',
    status: 'in_progress',
    tags: ['commercial', 'referral'],
    sourcePage: '/contact',
    ownerId: '4',
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: 'lead-7',
    websiteId: 'website-1',
    firstName: 'Amanda',
    lastName: 'Wilson',
    email: 'amanda.w@email.com',
    phone: '(555) 890-1234',
    message: 'Clogged drain in basement, need help ASAP.',
    status: 'new',
    tags: ['urgent', 'residential'],
    sourcePage: '/contact',
    createdAt: new Date('2024-01-26'),
    updatedAt: new Date('2024-01-26'),
  },
  {
    id: 'lead-8',
    websiteId: 'website-1',
    firstName: 'Thomas',
    lastName: 'Anderson',
    email: 'thomas.a@email.com',
    phone: '(555) 901-2345',
    message: 'Looking for someone to install new fixtures in master bath.',
    status: 'contacted',
    tags: ['residential', 'hot lead'],
    sourcePage: '/services',
    ownerId: '2',
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'lead-9',
    websiteId: 'website-1',
    firstName: 'Patricia',
    lastName: 'Moore',
    email: 'patricia.m@email.com',
    phone: '(555) 012-3456',
    message: 'Water pressure issues throughout the house.',
    status: 'lost',
    tags: ['residential'],
    sourcePage: '/contact',
    ownerId: '3',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: 'lead-10',
    websiteId: 'website-1',
    firstName: 'James',
    lastName: 'Jackson',
    email: 'james.j@business.com',
    phone: '(555) 123-4567',
    message: 'Need plumbing inspection for new commercial property.',
    status: 'new',
    tags: ['commercial', 'qualified', 'referral'],
    sourcePage: '/services',
    createdAt: new Date('2024-01-27'),
    updatedAt: new Date('2024-01-27'),
  },
  {
    id: 'lead-11',
    websiteId: 'website-1',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.g@email.com',
    phone: '(555) 234-5679',
    message: 'Interested in whole-house repiping.',
    status: 'in_progress',
    tags: ['residential', 'hot lead', 'qualified'],
    sourcePage: '/contact',
    ownerId: '1',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: 'lead-12',
    websiteId: 'website-1',
    firstName: 'Christopher',
    lastName: 'Lee',
    email: 'chris.lee@email.com',
    phone: '(555) 345-6790',
    message: 'Sump pump installation needed.',
    status: 'closed',
    tags: ['residential'],
    sourcePage: '/services',
    ownerId: '4',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-16'),
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    leadId: 'lead-2',
    title: 'Send commercial services quote',
    description: 'Prepare detailed quote for office building plumbing',
    dueDate: new Date('2024-01-26'),
    assignedUserId: '1',
    completed: false,
    createdAt: new Date('2024-01-24'),
  },
  {
    id: 'task-2',
    leadId: 'lead-3',
    title: 'Schedule site visit',
    description: 'Visit property to assess bathroom renovation requirements',
    dueDate: new Date('2024-01-27'),
    assignedUserId: '2',
    completed: false,
    createdAt: new Date('2024-01-23'),
  },
  {
    id: 'task-3',
    leadId: 'lead-1',
    title: 'Follow up call',
    description: 'Call to schedule appointment for kitchen faucet repair',
    dueDate: new Date('2024-01-26'),
    assignedUserId: '1',
    completed: false,
    createdAt: new Date('2024-01-25'),
  },
  {
    id: 'task-4',
    leadId: 'lead-3',
    title: 'Send preliminary estimate',
    description: 'Email rough estimate for bathroom renovation',
    dueDate: new Date('2024-01-25'),
    assignedUserId: '2',
    completed: true,
    createdAt: new Date('2024-01-20'),
    completedAt: new Date('2024-01-21'),
  },
  {
    id: 'task-5',
    leadId: 'lead-6',
    title: 'Schedule maintenance appointment',
    description: 'Coordinate with restaurant manager for annual maintenance visit',
    dueDate: new Date('2024-01-28'),
    assignedUserId: '4',
    completed: false,
    createdAt: new Date('2024-01-24'),
  },
  {
    id: 'task-6',
    leadId: 'lead-8',
    title: 'Send fixture options',
    description: 'Share catalog of bathroom fixtures with pricing',
    dueDate: new Date('2024-01-20'),
    assignedUserId: '2',
    completed: true,
    createdAt: new Date('2024-01-19'),
    completedAt: new Date('2024-01-20'),
  },
  {
    id: 'task-7',
    leadId: 'lead-11',
    title: 'Perform house inspection',
    description: 'Complete full inspection for repiping project',
    dueDate: new Date('2024-01-29'),
    assignedUserId: '1',
    completed: false,
    createdAt: new Date('2024-01-24'),
  },
];

export const mockNotes: Note[] = [
  {
    id: 'note-1',
    leadId: 'lead-2',
    userId: '1',
    content: 'Spoke with Mike. He needs a quote for 3-floor office building. Mentioned budget of $15-20k.',
    createdAt: new Date('2024-01-24T10:30:00'),
  },
  {
    id: 'note-2',
    leadId: 'lead-3',
    userId: '2',
    content: 'Emily wants to see material options before committing. Scheduled for next Tuesday.',
    createdAt: new Date('2024-01-23T14:15:00'),
  },
  {
    id: 'note-3',
    leadId: 'lead-3',
    userId: '2',
    content: 'Sent preliminary estimate of $8,500. Waiting for response.',
    createdAt: new Date('2024-01-21T09:00:00'),
  },
  {
    id: 'note-4',
    leadId: 'lead-4',
    userId: '3',
    content: 'Emergency call completed. Pipe repaired. Customer very satisfied with quick response.',
    createdAt: new Date('2024-01-19T16:45:00'),
  },
  {
    id: 'note-5',
    leadId: 'lead-6',
    userId: '4',
    content: 'Robert referred by Tony at Main Street Diner. Wants ongoing maintenance contract.',
    createdAt: new Date('2024-01-24T11:20:00'),
  },
  {
    id: 'note-6',
    leadId: 'lead-8',
    userId: '2',
    content: 'Thomas is interested in high-end fixtures. Budget is flexible.',
    createdAt: new Date('2024-01-22T13:30:00'),
  },
  {
    id: 'note-7',
    leadId: 'lead-9',
    userId: '3',
    content: 'Patricia went with another contractor due to price. Keep for future reference.',
    createdAt: new Date('2024-01-17T10:00:00'),
  },
  {
    id: 'note-8',
    leadId: 'lead-11',
    userId: '1',
    content: 'Maria is serious about the repiping. House is 40 years old, original plumbing.',
    createdAt: new Date('2024-01-24T15:45:00'),
  },
];
