import { Lead, Task } from '@/lib/types';

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    websiteId: 'website-1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@email.com',
    phone: '(555) 234-5678',
    message: 'I need help with a leaky faucet in my kitchen.',
    status: 'new',
    tags: ['urgent', 'residential'],
    sourcePage: '/contact',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'lead-2',
    websiteId: 'website-1',
    firstName: 'Mike',
    lastName: 'Davis',
    email: 'mike.davis@business.com',
    phone: '(555) 345-6789',
    message: 'Looking for commercial plumbing services for our office building.',
    status: 'contacted',
    tags: ['commercial'],
    sourcePage: '/contact',
    ownerId: '3',
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-24'),
  },
  {
    id: 'lead-3',
    websiteId: 'website-1',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'emily.r@email.com',
    phone: '(555) 456-7890',
    message: 'Need a quote for bathroom renovation plumbing.',
    status: 'in_progress',
    tags: ['residential', 'renovation'],
    sourcePage: '/services',
    ownerId: '3',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: 'lead-4',
    websiteId: 'website-1',
    firstName: 'David',
    lastName: 'Chen',
    email: 'david.chen@email.com',
    phone: '(555) 567-8901',
    message: 'Emergency - burst pipe in basement!',
    status: 'closed',
    tags: ['urgent', 'residential', 'emergency'],
    sourcePage: '/contact',
    ownerId: '3',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-19'),
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    leadId: 'lead-2',
    title: 'Send commercial services quote',
    description: 'Prepare detailed quote for office building plumbing',
    dueDate: new Date('2024-01-26'),
    assignedUserId: '3',
    completed: false,
    createdAt: new Date('2024-01-24'),
  },
  {
    id: 'task-2',
    leadId: 'lead-3',
    title: 'Schedule site visit',
    description: 'Visit property to assess bathroom renovation requirements',
    dueDate: new Date('2024-01-27'),
    assignedUserId: '3',
    completed: false,
    createdAt: new Date('2024-01-23'),
  },
  {
    id: 'task-3',
    leadId: 'lead-1',
    title: 'Follow up call',
    description: 'Call to schedule appointment for kitchen faucet repair',
    dueDate: new Date('2024-01-26'),
    assignedUserId: '3',
    completed: false,
    createdAt: new Date('2024-01-25'),
  },
];
