export interface Listing {
  id: string;
  address: string;
  description: string; // rich text (HTML string)
  listPrice: number;
  listingStatus: "active" | "sold" | "pending";
  representation?: string; // optional
  neighborhood: string;
  city: string;
  bedrooms: number;
  bathrooms: number;
  propertyType: string;
  yearBuilt: number;
  livingArea: number; // square feet
  lotArea: number;
  lotAreaUnit: string; // "acres" | "sq ft" etc.
  taxes: number; // annual
  listingBrokerage: string;
  mlsNumber: string;
  gallery: string[]; // array of image URLs
  thumbnail: string; // selected thumbnail image URL
}

export const listings: Listing[] = [
  {
    id: "1",
    address: "33289 Lakeview Court, Sundre, AB",
    description:
      "<p>Stunning lakefront property with panoramic views of the Rocky Mountains. This expansive estate features an open-concept living area with floor-to-ceiling windows, a gourmet kitchen with premium appliances, and a master suite with a private balcony overlooking the lake.</p><p>The property includes a heated garage, a private dock, and beautifully landscaped grounds with mature trees. Perfect for those seeking a luxurious mountain lifestyle with easy access to Sundre&rsquo;s amenities.</p>",
    listPrice: 1200000,
    listingStatus: "active",
    representation: "Seller",
    neighborhood: "Lakeview Estates",
    city: "Sundre",
    bedrooms: 5,
    bathrooms: 4,
    propertyType: "Detached",
    yearBuilt: 2018,
    livingArea: 3800,
    lotArea: 2.5,
    lotAreaUnit: "acres",
    taxes: 6200,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2045671",
    gallery: [
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/featured-3.webp",
      "/images/hero-bg.webp",
      "/images/buying-card.webp",
      "/images/selling-card.webp",
    ],
    thumbnail: "/images/featured-1.webp",
  },
  {
    id: "2",
    address: "22034 Lakeview Drive, Sundre, AB",
    description:
      "<p>A beautifully crafted home nestled along Lakeview Drive, offering serene water views and a private, treed setting. The main floor features a spacious great room with a stone fireplace, a chef&rsquo;s kitchen with a large island, and a dining area that opens to a wraparound deck.</p><p>Upstairs you&rsquo;ll find four generous bedrooms including a luxurious primary suite. The fully finished walkout basement provides additional living space with a rec room, wet bar, and guest bedroom.</p>",
    listPrice: 1350000,
    listingStatus: "active",
    neighborhood: "Lakeview",
    city: "Sundre",
    bedrooms: 5,
    bathrooms: 3.5,
    propertyType: "Detached",
    yearBuilt: 2020,
    livingArea: 4200,
    lotArea: 1.8,
    lotAreaUnit: "acres",
    taxes: 7100,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2051234",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-1.webp",
      "/images/featured-3.webp",
      "/images/hero-bg.webp",
      "/images/listings-card.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
  {
    id: "3",
    address: "33291 Lakeview Court, Sundre, AB",
    description:
      "<p>Contemporary ranch-style home on a generous lot in the sought-after Lakeview Estates community. This property boasts a modern open floor plan with vaulted ceilings, hardwood floors throughout, and a stunning kitchen with quartz countertops and a butler&rsquo;s pantry.</p><p>Enjoy outdoor living with a covered patio, hot tub area, and fenced yard backing onto green space. The triple attached garage offers ample storage and workshop space.</p>",
    listPrice: 1200000,
    listingStatus: "active",
    representation: "Buyer",
    neighborhood: "Lakeview Estates",
    city: "Sundre",
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Detached",
    yearBuilt: 2019,
    livingArea: 3200,
    lotArea: 1.5,
    lotAreaUnit: "acres",
    taxes: 5800,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2048890",
    gallery: [
      "/images/featured-3.webp",
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/contact-bg.webp",
      "/images/buying-card.webp",
    ],
    thumbnail: "/images/featured-3.webp",
  },
  {
    id: "4",
    address: "14422 Mountain View Road, Olds, AB",
    description:
      "<p>Impressive mountain-view property situated on a sprawling lot just minutes from the town of Olds. This home features a bright, airy interior with large windows framing the mountain panorama. The main level includes a formal living room, family room, and a gourmet kitchen with high-end finishes.</p><p>The walkout lower level offers a second family room, home theatre, and two additional bedrooms. Outside, enjoy a large deck, fire pit area, and direct trail access.</p>",
    listPrice: 985000,
    listingStatus: "active",
    neighborhood: "Mountain View",
    city: "Olds",
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Detached",
    yearBuilt: 2016,
    livingArea: 2900,
    lotArea: 3.2,
    lotAreaUnit: "acres",
    taxes: 5100,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2039456",
    gallery: [
      "/images/featured-1.webp",
      "/images/featured-3.webp",
      "/images/featured-2.webp",
      "/images/selling-card.webp",
    ],
    thumbnail: "/images/featured-1.webp",
  },
  {
    id: "5",
    address: "55123 Foothills Drive, Sundre, AB",
    description:
      "<p>An extraordinary estate property on the edge of the foothills, offering unmatched privacy and sweeping views. This custom-built home features a dramatic two-story great room, a chef&rsquo;s kitchen with a massive island, and a luxurious master wing with spa-like ensuite and walk-in closet.</p><p>The property includes a barn with corrals, riding arena, and fenced pastures — perfect for equestrian enthusiasts. Additional amenities include a heated shop, guest cabin, and irrigated gardens.</p>",
    listPrice: 2100000,
    listingStatus: "active",
    neighborhood: "Foothills",
    city: "Sundre",
    bedrooms: 6,
    bathrooms: 5,
    propertyType: "Acreage",
    yearBuilt: 2015,
    livingArea: 5200,
    lotArea: 40,
    lotAreaUnit: "acres",
    taxes: 9800,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2062345",
    gallery: [
      "/images/featured-3.webp",
      "/images/featured-2.webp",
      "/images/featured-1.webp",
      "/images/hero-bg.webp",
      "/images/listings-card.webp",
      "/images/buying-card.webp",
    ],
    thumbnail: "/images/featured-3.webp",
  },
  {
    id: "6",
    address: "88012 Range Road 40, Sundre, AB",
    description:
      "<p>A picturesque ranch property with a beautifully renovated farmhouse, set against the backdrop of the Canadian Rockies. The home combines original character with modern updates including a new kitchen, renovated bathrooms, and updated mechanical systems.</p><p>The ranch includes a large barn, multiple outbuildings, and fenced pastures ideal for cattle or horses. A seasonal creek runs through the property adding to its natural beauty.</p>",
    listPrice: 1750000,
    listingStatus: "active",
    neighborhood: "Rural Sundre",
    city: "Sundre",
    bedrooms: 4,
    bathrooms: 2.5,
    propertyType: "Ranch/Farm",
    yearBuilt: 1985,
    livingArea: 2600,
    lotArea: 160,
    lotAreaUnit: "acres",
    taxes: 4200,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2071890",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-1.webp",
      "/images/featured-3.webp",
      "/images/selling-card.webp",
      "/images/contact-bg.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
  {
    id: "7",
    address: "4510 Willow Creek Road, Olds, AB",
    description:
      "<p>Charming country home on a peaceful acreage near Olds. Features an updated kitchen, cozy living spaces, and a wonderful screened porch overlooking the garden. The property is well-maintained with a new roof, windows, and HVAC system.</p><p>Includes a detached double garage and workshop. The landscaped yard features perennial gardens, mature trees, and a large vegetable garden area. Minutes from schools, shopping, and recreational facilities.</p>",
    listPrice: 685000,
    listingStatus: "active",
    neighborhood: "Willow Creek",
    city: "Olds",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Detached",
    yearBuilt: 2002,
    livingArea: 1800,
    lotArea: 5,
    lotAreaUnit: "acres",
    taxes: 3400,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2080123",
    gallery: [
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/featured-3.webp",
      "/images/hero-bg.webp",
    ],
    thumbnail: "/images/featured-1.webp",
  },
  {
    id: "8",
    address: "29100 Township Road 320, Sundre, AB",
    description:
      "<p>Premium country estate with a stunning custom-built bungalow offering mountain views from every room. The home features an open floor plan with soaring ceilings, a stone fireplace, and a kitchen designed for entertaining with top-of-the-line appliances.</p><p>The walkout basement includes a media room, games area, and two additional bedrooms. Outside, enjoy a large deck with a built-in BBQ, landscaped yard, and a triple heated garage.</p>",
    listPrice: 1425000,
    listingStatus: "active",
    neighborhood: "Township Heights",
    city: "Sundre",
    bedrooms: 5,
    bathrooms: 3.5,
    propertyType: "Acreage",
    yearBuilt: 2021,
    livingArea: 3600,
    lotArea: 10,
    lotAreaUnit: "acres",
    taxes: 6800,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2085567",
    gallery: [
      "/images/featured-3.webp",
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/buying-card.webp",
      "/images/selling-card.webp",
    ],
    thumbnail: "/images/featured-3.webp",
  },
  {
    id: "9",
    address: "7723 Pine Ridge Trail, Sundre, AB",
    description:
      "<p>A stunning timber-frame home situated in a private, forested setting along Pine Ridge Trail. The soaring cathedral ceilings and exposed beams create a warm, lodge-like atmosphere throughout the main living areas.</p><p>Features include a gourmet kitchen, main-floor master suite, and a loft office with valley views. The wraparound deck and hot tub provide the perfect space for relaxation. Trails from the property lead directly into Crown land.</p>",
    listPrice: 1150000,
    listingStatus: "active",
    neighborhood: "Pine Ridge",
    city: "Sundre",
    bedrooms: 3,
    bathrooms: 2.5,
    propertyType: "Detached",
    yearBuilt: 2017,
    livingArea: 2400,
    lotArea: 4,
    lotAreaUnit: "acres",
    taxes: 5500,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2091234",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-3.webp",
      "/images/featured-1.webp",
      "/images/listings-card.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
  {
    id: "10",
    address: "16200 Highway 27, Sundre, AB",
    description:
      "<p>Exceptional equestrian property with a modern family home and complete horse facilities. The home offers a bright, open floor plan with high-end finishes, a large mudroom with boot wash, and a bonus room above the garage.</p><p>The equestrian facilities include a 6-stall barn, tack room, hay storage, outdoor riding arena, and round pen. Multiple fenced paddocks and pastures, with water to each. Trail access directly from the property.</p>",
    listPrice: 1895000,
    listingStatus: "active",
    representation: "Seller",
    neighborhood: "Highway 27 Corridor",
    city: "Sundre",
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Ranch/Farm",
    yearBuilt: 2014,
    livingArea: 3100,
    lotArea: 80,
    lotAreaUnit: "acres",
    taxes: 7200,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2095678",
    gallery: [
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/featured-3.webp",
      "/images/hero-bg.webp",
      "/images/contact-bg.webp",
    ],
    thumbnail: "/images/featured-1.webp",
  },
  {
    id: "11",
    address: "5500 Bearberry Road, Sundre, AB",
    description:
      "<p>Private retreat on a beautifully treed lot along Bearberry Road. This well-maintained home features a warm, inviting interior with hardwood floors, a river rock fireplace, and a sunroom overlooking the gardens.</p><p>The property includes a detached workshop, greenhouse, and established fruit trees. A peaceful setting with abundant wildlife, yet only 15 minutes from Sundre.</p>",
    listPrice: 725000,
    listingStatus: "active",
    neighborhood: "Bearberry",
    city: "Sundre",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Detached",
    yearBuilt: 2005,
    livingArea: 2100,
    lotArea: 8,
    lotAreaUnit: "acres",
    taxes: 3800,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2098901",
    gallery: [
      "/images/featured-3.webp",
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/selling-card.webp",
    ],
    thumbnail: "/images/featured-3.webp",
  },
  {
    id: "12",
    address: "9901 Clearwater Lane, Caroline, AB",
    description:
      "<p>Gorgeous riverside property in the Caroline area with direct access to the Clearwater River. This log home offers authentic mountain living with modern comforts, including radiant floor heating, a gourmet kitchen, and a master suite with river views.</p><p>The expansive deck overlooks the river and surrounding forest. Includes a guest cabin, boat launch area, and miles of trails on the property. World-class fishing at your doorstep.</p>",
    listPrice: 1580000,
    listingStatus: "active",
    neighborhood: "Clearwater",
    city: "Caroline",
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Acreage",
    yearBuilt: 2012,
    livingArea: 2800,
    lotArea: 20,
    lotAreaUnit: "acres",
    taxes: 5900,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2102345",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-3.webp",
      "/images/featured-1.webp",
      "/images/buying-card.webp",
      "/images/hero-bg.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
  {
    id: "18",
    address: "11200 River Bend Road, Sundre, AB",
    description:
      "<p>Spectacular riverfront estate with over 500 feet of private river frontage. The custom-built home features floor-to-ceiling windows, a dramatic stone fireplace, and a chef&rsquo;s kitchen with premium finishes throughout.</p><p>The property includes a private boat launch, fire pit area, and beautifully manicured grounds. A truly one-of-a-kind offering in the Sundre area.</p>",
    listPrice: 2350000,
    listingStatus: "active",
    representation: "Seller",
    neighborhood: "River Bend",
    city: "Sundre",
    bedrooms: 5,
    bathrooms: 4.5,
    propertyType: "Acreage",
    yearBuilt: 2022,
    livingArea: 4800,
    lotArea: 12,
    lotAreaUnit: "acres",
    taxes: 10200,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2110456",
    gallery: [
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/featured-3.webp",
      "/images/hero-bg.webp",
    ],
    thumbnail: "/images/featured-1.webp",
  },
  {
    id: "19",
    address: "45600 Range Road 62, Olds, AB",
    description:
      "<p>Outstanding cattle ranch with a well-maintained homestead and excellent agricultural infrastructure. The home has been tastefully updated while maintaining its classic farmhouse charm.</p><p>Includes a large calving barn, hay storage, corrals, and cross-fenced pastures with water to each. Excellent grazing land with a mix of native and tame grasses.</p>",
    listPrice: 1980000,
    listingStatus: "active",
    neighborhood: "Rural Olds",
    city: "Olds",
    bedrooms: 4,
    bathrooms: 2.5,
    propertyType: "Ranch/Farm",
    yearBuilt: 1988,
    livingArea: 2200,
    lotArea: 240,
    lotAreaUnit: "acres",
    taxes: 3900,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2115789",
    gallery: [
      "/images/featured-3.webp",
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/selling-card.webp",
    ],
    thumbnail: "/images/featured-3.webp",
  },
  {
    id: "20",
    address: "3300 Mountainview Crescent, Sundre, AB",
    description:
      "<p>Modern family home in a quiet cul-de-sac with stunning mountain views. The open-concept main floor features a bright living room, a kitchen with a large island, and direct access to a covered deck.</p><p>Three bedrooms upstairs plus a bonus room. The finished basement includes a fourth bedroom, bathroom, and rec room. Attached double garage and fully landscaped yard.</p>",
    listPrice: 545000,
    listingStatus: "active",
    neighborhood: "Mountainview",
    city: "Sundre",
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Detached",
    yearBuilt: 2020,
    livingArea: 2000,
    lotArea: 7200,
    lotAreaUnit: "sq ft",
    taxes: 3200,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2120123",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-3.webp",
      "/images/featured-1.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
  {
    id: "13",
    address: "78901 Range Road 54, Sundre, AB",
    description:
      "<p>This beautiful property was sold representing the buyer. A wonderful ranch setting with incredible mountain views and well-maintained improvements. The home features an updated kitchen, cozy living spaces, and a fantastic outdoor entertaining area.</p><p>The ranch includes a large shop, corrals, and excellent fencing throughout. Water rights included with the property.</p>",
    listPrice: 1475000,
    listingStatus: "sold",
    representation: "Buyer",
    neighborhood: "Rural Sundre",
    city: "Sundre",
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Ranch/Farm",
    yearBuilt: 2010,
    livingArea: 2700,
    lotArea: 120,
    lotAreaUnit: "acres",
    taxes: 4800,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2015678",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-1.webp",
      "/images/featured-3.webp",
      "/images/hero-bg.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
  {
    id: "14",
    address: "12500 Mountain Avenue, Sundre, AB",
    description:
      "<p>Charming family home on a generous lot in Sundre. This home was sold representing the seller and features beautiful updates including a renovated kitchen, new flooring, and a finished basement with a rec room and fourth bedroom.</p><p>The large, fenced backyard is perfect for families, with a playset area, garden beds, and a covered patio. Walking distance to schools and parks.</p>",
    listPrice: 485000,
    listingStatus: "sold",
    representation: "Seller",
    neighborhood: "Mountain Avenue",
    city: "Sundre",
    bedrooms: 4,
    bathrooms: 2,
    propertyType: "Detached",
    yearBuilt: 1998,
    livingArea: 1600,
    lotArea: 8500,
    lotAreaUnit: "sq ft",
    taxes: 2900,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2022345",
    gallery: [
      "/images/featured-3.webp",
      "/images/featured-2.webp",
      "/images/featured-1.webp",
    ],
    thumbnail: "/images/featured-3.webp",
  },
  {
    id: "15",
    address: "6780 Ridgeview Place, Olds, AB",
    description:
      "<p>Executive bungalow in Olds&rsquo; premier Ridgeview neighbourhood. Sold representing the seller, this home featured a stunning open floor plan, a chef&rsquo;s kitchen with a large island, and a master suite with a luxury ensuite bathroom.</p><p>The fully developed walkout basement includes a rec room, wet bar, and guest suite. The landscaped yard backs onto a pond with walking paths.</p>",
    listPrice: 795000,
    listingStatus: "sold",
    neighborhood: "Ridgeview",
    city: "Olds",
    bedrooms: 3,
    bathrooms: 2.5,
    propertyType: "Detached",
    yearBuilt: 2019,
    livingArea: 2200,
    lotArea: 10500,
    lotAreaUnit: "sq ft",
    taxes: 4100,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2028901",
    gallery: [
      "/images/featured-1.webp",
      "/images/featured-3.webp",
      "/images/featured-2.webp",
      "/images/selling-card.webp",
    ],
    thumbnail: "/images/featured-1.webp",
  },
  {
    id: "16",
    address: "34020 Westward Ho Road, Sundre, AB",
    description:
      "<p>Sprawling ranch property with a renovated farmhouse and excellent agricultural improvements. Sold representing the buyer, this property offered incredible value with fertile land, water rights, and mountain views.</p><p>The home features a new kitchen, updated bathrooms, and a cozy living room with a wood-burning fireplace. Outbuildings include a large shop, cattle barn, and corrals.</p>",
    listPrice: 1650000,
    listingStatus: "sold",
    neighborhood: "Westward Ho",
    city: "Sundre",
    bedrooms: 5,
    bathrooms: 3,
    propertyType: "Ranch/Farm",
    yearBuilt: 1992,
    livingArea: 2400,
    lotArea: 320,
    lotAreaUnit: "acres",
    taxes: 3600,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2032456",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-1.webp",
      "/images/featured-3.webp",
      "/images/contact-bg.webp",
      "/images/listings-card.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
  {
    id: "17",
    address: "2200 Elkton Drive, Sundre, AB",
    description:
      "<p>Beautiful townhome in the heart of Sundre. This well-maintained property features an open main floor with modern finishes, a gas fireplace, and a kitchen with stainless steel appliances and granite countertops.</p><p>Includes a private fenced patio, single attached garage, and is within walking distance of downtown shops and restaurants. Low maintenance living at its finest.</p>",
    listPrice: 345000,
    listingStatus: "sold",
    neighborhood: "Elkton",
    city: "Sundre",
    bedrooms: 2,
    bathrooms: 1.5,
    propertyType: "Townhouse",
    yearBuilt: 2015,
    livingArea: 1200,
    lotArea: 2800,
    lotAreaUnit: "sq ft",
    taxes: 2100,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2035789",
    gallery: [
      "/images/featured-3.webp",
      "/images/featured-2.webp",
      "/images/featured-1.webp",
    ],
    thumbnail: "/images/featured-3.webp",
  },
  {
    id: "21",
    address: "8800 Heritage Lane, Sundre, AB",
    description:
      "<p>Beautifully restored heritage home in the heart of Sundre. Original hardwood floors, crown mouldings, and a wraparound porch have been lovingly preserved alongside modern updates including a new kitchen, bathrooms, and mechanical systems.</p><p>The large lot includes a detached garage, mature landscaping, and a private backyard garden. Walking distance to downtown Sundre.</p>",
    listPrice: 425000,
    listingStatus: "sold",
    representation: "Seller",
    neighborhood: "Heritage District",
    city: "Sundre",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Detached",
    yearBuilt: 1952,
    livingArea: 1400,
    lotArea: 9000,
    lotAreaUnit: "sq ft",
    taxes: 2400,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2040567",
    gallery: [
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/featured-3.webp",
    ],
    thumbnail: "/images/featured-1.webp",
  },
  {
    id: "22",
    address: "19500 Township Road 340, Olds, AB",
    description:
      "<p>Premium acreage with a custom-built walkout bungalow and panoramic mountain views. The home features an impressive great room with soaring ceilings and a floor-to-ceiling stone fireplace.</p><p>The fully finished walkout basement includes a home theatre, wet bar, and guest suite. Includes a heated shop, fenced pastures, and a small barn.</p>",
    listPrice: 1125000,
    listingStatus: "sold",
    neighborhood: "Township",
    city: "Olds",
    bedrooms: 4,
    bathrooms: 3.5,
    propertyType: "Acreage",
    yearBuilt: 2017,
    livingArea: 3000,
    lotArea: 15,
    lotAreaUnit: "acres",
    taxes: 5600,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2042890",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-1.webp",
      "/images/featured-3.webp",
      "/images/buying-card.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
  {
    id: "23",
    address: "7100 Spruce Meadows Road, Sundre, AB",
    description:
      "<p>Stunning estate on a private, treed lot with mountain views. This home features a grand foyer, formal dining room, and a gourmet kitchen with top-of-the-line appliances.</p><p>The master suite includes a spa-like ensuite and a private balcony. Additional features include a home office, wine cellar, and a triple heated garage with workshop.</p>",
    listPrice: 1850000,
    listingStatus: "sold",
    representation: "Buyer",
    neighborhood: "Spruce Meadows",
    city: "Sundre",
    bedrooms: 5,
    bathrooms: 4,
    propertyType: "Detached",
    yearBuilt: 2016,
    livingArea: 4100,
    lotArea: 5,
    lotAreaUnit: "acres",
    taxes: 8200,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2045123",
    gallery: [
      "/images/featured-3.webp",
      "/images/featured-2.webp",
      "/images/featured-1.webp",
      "/images/hero-bg.webp",
      "/images/selling-card.webp",
    ],
    thumbnail: "/images/featured-3.webp",
  },
  {
    id: "24",
    address: "2800 Aspen Grove Way, Caroline, AB",
    description:
      "<p>Peaceful retreat surrounded by aspen groves with views of the foothills. This log-style home offers a warm, inviting atmosphere with an open great room, stone fireplace, and a loft office.</p><p>The property includes a workshop, garden shed, and is adjacent to Crown land for endless recreational opportunities.</p>",
    listPrice: 595000,
    listingStatus: "sold",
    neighborhood: "Aspen Grove",
    city: "Caroline",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Detached",
    yearBuilt: 2008,
    livingArea: 1800,
    lotArea: 10,
    lotAreaUnit: "acres",
    taxes: 3100,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2047456",
    gallery: [
      "/images/featured-1.webp",
      "/images/featured-3.webp",
      "/images/featured-2.webp",
    ],
    thumbnail: "/images/featured-1.webp",
  },
  {
    id: "25",
    address: "5200 Sunset Ridge, Sundre, AB",
    description:
      "<p>Executive home in Sundre&rsquo;s desirable Sunset Ridge community. Features a contemporary design with clean lines, an open floor plan, and a stunning kitchen with waterfall island.</p><p>The covered rooftop patio offers 360-degree views. Includes a triple garage, fully landscaped yard with irrigation, and a hot tub deck.</p>",
    listPrice: 875000,
    listingStatus: "sold",
    representation: "Seller",
    neighborhood: "Sunset Ridge",
    city: "Sundre",
    bedrooms: 4,
    bathrooms: 3.5,
    propertyType: "Detached",
    yearBuilt: 2021,
    livingArea: 2600,
    lotArea: 8800,
    lotAreaUnit: "sq ft",
    taxes: 4500,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2049789",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-1.webp",
      "/images/featured-3.webp",
      "/images/contact-bg.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
  {
    id: "26",
    address: "14000 Meadow Creek Drive, Olds, AB",
    description:
      "<p>Well-maintained family home in the Meadow Creek neighbourhood. Updated kitchen with new cabinets and countertops, refreshed bathrooms, and new flooring throughout the main level.</p><p>The finished basement provides extra living space with a rec room and additional bedroom. Large fenced backyard with a shed and mature trees.</p>",
    listPrice: 380000,
    listingStatus: "sold",
    neighborhood: "Meadow Creek",
    city: "Olds",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Detached",
    yearBuilt: 2004,
    livingArea: 1500,
    lotArea: 6500,
    lotAreaUnit: "sq ft",
    taxes: 2200,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2052012",
    gallery: [
      "/images/featured-3.webp",
      "/images/featured-2.webp",
      "/images/featured-1.webp",
    ],
    thumbnail: "/images/featured-3.webp",
  },
  {
    id: "27",
    address: "61500 Range Road 70, Sundre, AB",
    description:
      "<p>Expansive ranch with a newer custom home and world-class equestrian facilities. The home features a grand open living area, chef&rsquo;s kitchen, and a luxurious master wing.</p><p>Equestrian amenities include an indoor riding arena, 12-stall barn, and miles of riding trails on the property. Fenced and cross-fenced with water throughout.</p>",
    listPrice: 3200000,
    listingStatus: "sold",
    representation: "Buyer",
    neighborhood: "Rural Sundre West",
    city: "Sundre",
    bedrooms: 6,
    bathrooms: 5,
    propertyType: "Ranch/Farm",
    yearBuilt: 2013,
    livingArea: 5500,
    lotArea: 200,
    lotAreaUnit: "acres",
    taxes: 8900,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2054345",
    gallery: [
      "/images/featured-1.webp",
      "/images/featured-2.webp",
      "/images/featured-3.webp",
      "/images/hero-bg.webp",
      "/images/listings-card.webp",
    ],
    thumbnail: "/images/featured-1.webp",
  },
  {
    id: "28",
    address: "3600 Hilltop Terrace, Sundre, AB",
    description:
      "<p>Elevated hilltop property with commanding views of the valley and mountains beyond. This modern rancher features a clean, contemporary design with an open floor plan and walls of glass.</p><p>The large covered deck is perfect for entertaining. Includes a double attached garage and low-maintenance landscaping designed for the Alberta climate.</p>",
    listPrice: 620000,
    listingStatus: "sold",
    neighborhood: "Hilltop",
    city: "Sundre",
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Detached",
    yearBuilt: 2019,
    livingArea: 1700,
    lotArea: 7500,
    lotAreaUnit: "sq ft",
    taxes: 3000,
    listingBrokerage: "RE/MAX House of Real Estate",
    mlsNumber: "A2056678",
    gallery: [
      "/images/featured-2.webp",
      "/images/featured-3.webp",
      "/images/featured-1.webp",
    ],
    thumbnail: "/images/featured-2.webp",
  },
];

export function getActiveListings(): Listing[] {
  return listings.filter((l) => l.listingStatus === "active");
}

export function getSoldListings(): Listing[] {
  return listings.filter((l) => l.listingStatus === "sold");
}

export function getListingById(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency: "CAD",
    maximumFractionDigits: 0,
  }).format(price);
}
