import { Review } from '../types';

export const mockGoogleReviews: Review[] = [
  {
    id: 'review-1',
    name: 'Pitt meadows Canuck',
    rating: 5,
    text: 'I had an excellent experience with Premier Grounds Contracting. From the initial quote to the final walk-through, their team was professional, courteous, and highly skilled. They completed our backyard transformation ahead of schedule and the results exceeded our expectations.',
    date: '8 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-2',
    name: 'Gabe Stevens',
    rating: 5,
    text: 'As an arborist and sole proprietor, it\'s absolutely essential for me to collaborate with people who are not only reliable and skilled, but who also share my commitment to quality and professionalism. Premier Grounds Contracting has been an outstanding partner in this regard.',
    date: '9 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-3',
    name: 'Jacquie Pellerdi',
    rating: 5,
    text: 'Premier Grounds Contracting exceeded my expectations. Love my new artificial turf and river rock landscaped garden! Not only does it look amazing, but I also appreciate how low-maintenance it is. The team was professional, punctual, and left the site spotless. Highly recommend!',
    date: '11 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-4',
    name: 'Karen',
    rating: 5,
    text: 'I recently hired Premier Grounds Contracting to complete some landscaping work around my property, and my experience was outstanding from start to finish. The team was professional, efficient, and clearly passionate about their craft. I couldn\'t be happier with the results!',
    date: '11 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-5',
    name: 'Paul Geordie',
    rating: 5,
    text: 'Premier Grounds Contracting transformed my yard efficiently and professionally. Their expert team installed our artificial turf beautifully and left everything clean. The quality speaks for itself - highly recommend their services for any landscaping project!',
    date: '11 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-6',
    name: 'Sarah Mitchell',
    rating: 4,
    text: 'Great service overall. The crew was friendly and worked hard to complete our patio installation. There was a minor delay due to weather, but they communicated well and made up for lost time. Very satisfied with the final product.',
    date: '7 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-7',
    name: 'Michael Chen',
    rating: 5,
    text: 'Exceptional attention to detail! They transformed our front yard with beautiful native plantings and a new stone pathway. The designer really listened to our vision and brought it to life. Worth every penny.',
    date: '6 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-8',
    name: 'Jennifer Walsh',
    rating: 5,
    text: 'We hired them for a complete backyard makeover including deck, pergola, and garden beds. The project manager kept us informed every step of the way. The craftsmanship is top-notch and our backyard is now our favorite place to relax!',
    date: '5 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-9',
    name: 'David Thompson',
    rating: 4,
    text: 'Very professional team. They installed our irrigation system and did lawn restoration. The work quality is excellent. Only giving 4 stars because the initial quote was slightly off, but they worked with us on the final price.',
    date: '4 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-10',
    name: 'Lisa Rodriguez',
    rating: 5,
    text: 'Outstanding service from quote to completion! They built beautiful retaining walls and planted gorgeous perennials. The crew was respectful of our property and cleaned up thoroughly every day. Can\'t recommend them enough!',
    date: '3 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-11',
    name: 'Robert Anderson',
    rating: 5,
    text: 'Premier Grounds Contracting did an amazing job on our drainage issues. No more flooding in the backyard! They were quick, efficient, and the pricing was fair. Will definitely use them again for future projects.',
    date: '2 months ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-12',
    name: 'Emma Williams',
    rating: 4,
    text: 'Good experience overall. They installed sod and did some garden cleanup. The team was friendly and hardworking. Final result looks great, though I wish they had offered more design suggestions upfront.',
    date: '1 month ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-13',
    name: 'James Patterson',
    rating: 5,
    text: 'Fantastic work on our outdoor lighting and landscaping! The evening ambiance they created is magical. Professional, creative, and delivered exactly what we wanted. Thank you for making our outdoor space special!',
    date: '3 weeks ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-14',
    name: 'Maria Santos',
    rating: 5,
    text: 'We\'ve used several landscaping companies over the years, and Premier Grounds Contracting is by far the best. They redesigned our entire property with incredible attention to detail. The quality of their work is unmatched!',
    date: '2 weeks ago',
    avatar: '',
    source: 'google',
  },
  {
    id: 'review-15',
    name: 'Thomas Lee',
    rating: 4,
    text: 'Solid work on our fence installation and garden upgrade. The team showed up on time every day and worked efficiently. Communication could have been better during the project, but the end result is exactly what we wanted.',
    date: '1 week ago',
    avatar: '',
    source: 'google',
  },
];
